//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelAppC.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelAppC.Shared.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adults.
        /// </summary>
        public static string adults {
            get {
                return ResourceManager.GetString("adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Rooms.
        /// </summary>
        public static string Back_to_Rooms {
            get {
                return ResourceManager.GetString("Back to Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked Room.
        /// </summary>
        public static string Booked_Room {
            get {
                return ResourceManager.GetString("Booked Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In Date.
        /// </summary>
        public static string Check_In_Date {
            get {
                return ResourceManager.GetString("Check In Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out Date.
        /// </summary>
        public static string Check_Out_Date {
            get {
                return ResourceManager.GetString("Check Out Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Now.
        /// </summary>
        public static string Checkout_Now {
            get {
                return ResourceManager.GetString("Checkout Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password....
        /// </summary>
        public static string Confirm_Password___ {
            get {
                return ResourceManager.GetString("Confirm Password...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost for.
        /// </summary>
        public static string Cost_for {
            get {
                return ResourceManager.GetString("Cost for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Room.
        /// </summary>
        public static string Double_Room {
            get {
                return ResourceManager.GetString("Double Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email....
        /// </summary>
        public static string Email___ {
            get {
                return ResourceManager.GetString("Email...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy the exercises that keep you looking and feeling great..
        /// </summary>
        public static string Enjoy_the_exercises_that_keep_you_looking_and_feeling_great_ {
            get {
                return ResourceManager.GetString("Enjoy the exercises that keep you looking and feeling great.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy your special cofee as you have a luxe Nespresso machine..
        /// </summary>
        public static string Enjoy_your_special_cofee_as_you_have_a_luxe_Nespresso_machine_ {
            get {
                return ResourceManager.GetString("Enjoy your special cofee as you have a luxe Nespresso machine.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Details.
        /// </summary>
        public static string Enter_Details {
            get {
                return ResourceManager.GetString("Enter Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore our Amenities.
        /// </summary>
        public static string Explore_our_Amenities {
            get {
                return ResourceManager.GetString("Explore our Amenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness center.
        /// </summary>
        public static string Fitness_center {
            get {
                return ResourceManager.GetString("Fitness center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Parking.
        /// </summary>
        public static string Free_Parking {
            get {
                return ResourceManager.GetString("Free Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Wifi.
        /// </summary>
        public static string Free_Wifi {
            get {
                return ResourceManager.GetString("Free Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Many Nights?.
        /// </summary>
        public static string How_Many_Nights_ {
            get {
                return ResourceManager.GetString("How Many Nights?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just relax and enjoy our healthy pool.
        /// </summary>
        public static string Just_relax_and_enjoy_our_healthy_pool {
            get {
                return ResourceManager.GetString("Just relax and enjoy our healthy pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King Room.
        /// </summary>
        public static string King_Room {
            get {
                return ResourceManager.GetString("King Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like their human companions, dogs and cats should enjoy too..
        /// </summary>
        public static string Like_their_human_companions__dogs_and_cats_should_enjoy_too_ {
            get {
                return ResourceManager.GetString("Like their human companions, dogs and cats should enjoy too.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Suite.
        /// </summary>
        public static string Master_Suite {
            get {
                return ResourceManager.GetString("Master Suite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Occupancy.
        /// </summary>
        public static string Max_Occupancy {
            get {
                return ResourceManager.GetString("Max Occupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number....
        /// </summary>
        public static string Mobile_Number___ {
            get {
                return ResourceManager.GetString("Mobile Number...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name....
        /// </summary>
        public static string Name___ {
            get {
                return ResourceManager.GetString("Name...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nights.
        /// </summary>
        public static string nights {
            get {
                return ResourceManager.GetString("nights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Nights.
        /// </summary>
        public static string No__Of_Nights {
            get {
                return ResourceManager.GetString("No. Of Nights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Nights.
        /// </summary>
        public static string No_Of_Nights {
            get {
                return ResourceManager.GetString("No Of Nights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our residents enjoy our sparkling swimming pool and spa, fitness center, and community playground. Each Room is equipped with an in-home washer and dryer set, private patio or balcony, and plenty of storage space..
        /// </summary>
        public static string Our_residents_enjoy_our_sparkling_swimming_pool_and_spa__fitness_center__and_community_playground__Each_Room_is_equipped_with_an_in_home_washer_and_dryer_set__private_patio_or_balcony__and_plenty_of_storage_space_ {
            get {
                return ResourceManager.GetString("Our residents enjoy our sparkling swimming pool and spa, fitness center, and comm" +
                        "unity playground. Each Room is equipped with an in-home washer and dryer set, pr" +
                        "ivate patio or balcony, and plenty of storage space.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password....
        /// </summary>
        public static string Password___ {
            get {
                return ResourceManager.GetString("Password...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Friendly.
        /// </summary>
        public static string Pet_Friendly {
            get {
                return ResourceManager.GetString("Pet Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen Room.
        /// </summary>
        public static string Queen_Room {
            get {
                return ResourceManager.GetString("Queen Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Register_as_a_new_user {
            get {
                return ResourceManager.GetString("Register as a new user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Details.
        /// </summary>
        public static string Room_Details {
            get {
                return ResourceManager.GetString("Room Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Size.
        /// </summary>
        public static string Room_Size {
            get {
                return ResourceManager.GetString("Room Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Room.
        /// </summary>
        public static string Single_Room {
            get {
                return ResourceManager.GetString("Single Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Cofee.
        /// </summary>
        public static string Special_Cofee {
            get {
                return ResourceManager.GetString("Special Cofee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        public static string Studio {
            get {
                return ResourceManager.GetString("Studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimming Pool.
        /// </summary>
        public static string Swimming_Pool {
            get {
                return ResourceManager.GetString("Swimming Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple Room.
        /// </summary>
        public static string Triple_Room {
            get {
                return ResourceManager.GetString("Triple Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we provide free high speed wifi connection.
        /// </summary>
        public static string we_provide_free_high_speed_wifi_connection {
            get {
                return ResourceManager.GetString("we provide free high speed wifi connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you stay with us your parking is complimentary.
        /// </summary>
        public static string When_you_stay_with_us_your_parking_is_complimentary {
            get {
                return ResourceManager.GetString("When you stay with us your parking is complimentary", resourceCulture);
            }
        }
    }
}
